/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContentStudioRouteImport } from './routes/content-studio'
import { Route as DailyExecutionRouteImport } from './routes/daily-execution'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DesignRouteImport } from './routes/design'
import { Route as EmailCenterRouteImport } from './routes/email-center'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FunnelAuditRouteImport } from './routes/funnel-audit'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LeadControlRouteImport } from './routes/lead-control'
import { Route as LeadJournalRouteImport } from './routes/lead-journal'
import { Route as LeadsDetailRouteImport } from './routes/leads-detail'
import { Route as MarketingMeetingsRouteImport } from './routes/marketing-meetings'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MediaRegisterRouteImport } from './routes/media-register'
import { Route as NewLeadRouteImport } from './routes/new-lead'
import { Route as OkrsRouteImport } from './routes/okrs'
import { Route as PartnerPortalRouteImport } from './routes/partner-portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as RealtorPortalRouteImport } from './routes/realtor-portal'
import { Route as RetentionRouteImport } from './routes/retention'
import { Route as RevenueCommandRouteImport } from './routes/revenue-command'
import { Route as RoleGovernanceRouteImport } from './routes/role-governance'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamDirectoryRouteImport } from './routes/team-directory'
import { Route as TurnaroundRouteImport } from './routes/turnaround'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as WorkdeskRouteImport } from './routes/workdesk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentStudioRoute = ContentStudioRouteImport.update({
  id: '/content-studio',
  path: '/content-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyExecutionRoute = DailyExecutionRouteImport.update({
  id: '/daily-execution',
  path: '/daily-execution',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailCenterRoute = EmailCenterRouteImport.update({
  id: '/email-center',
  path: '/email-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelAuditRoute = FunnelAuditRouteImport.update({
  id: '/funnel-audit',
  path: '/funnel-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadControlRoute = LeadControlRouteImport.update({
  id: '/lead-control',
  path: '/lead-control',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadJournalRoute = LeadJournalRouteImport.update({
  id: '/lead-journal',
  path: '/lead-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsDetailRoute = LeadsDetailRouteImport.update({
  id: '/leads-detail',
  path: '/leads-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingMeetingsRoute = MarketingMeetingsRouteImport.update({
  id: '/marketing-meetings',
  path: '/marketing-meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRegisterRoute = MediaRegisterRouteImport.update({
  id: '/media-register',
  path: '/media-register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewLeadRoute = NewLeadRouteImport.update({
  id: '/new-lead',
  path: '/new-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const OkrsRoute = OkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPortalRoute = PartnerPortalRouteImport.update({
  id: '/partner-portal',
  path: '/partner-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtorPortalRoute = RealtorPortalRouteImport.update({
  id: '/realtor-portal',
  path: '/realtor-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RetentionRoute = RetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueCommandRoute = RevenueCommandRouteImport.update({
  id: '/revenue-command',
  path: '/revenue-command',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleGovernanceRoute = RoleGovernanceRouteImport.update({
  id: '/role-governance',
  path: '/role-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamDirectoryRoute = TeamDirectoryRouteImport.update({
  id: '/team-directory',
  path: '/team-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnaroundRoute = TurnaroundRouteImport.update({
  id: '/turnaround',
  path: '/turnaround',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkdeskRoute = WorkdeskRouteImport.update({
  id: '/workdesk',
  path: '/workdesk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/coaching': typeof CoachingRoute
  '/compliance': typeof ComplianceRoute
  '/content-studio': typeof ContentStudioRoute
  '/daily-execution': typeof DailyExecutionRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/email-center': typeof EmailCenterRoute
  '/forecast': typeof ForecastRoute
  '/funnel-audit': typeof FunnelAuditRoute
  '/handoff': typeof HandoffRoute
  '/integrations': typeof IntegrationsRoute
  '/lead-control': typeof LeadControlRoute
  '/lead-journal': typeof LeadJournalRoute
  '/leads-detail': typeof LeadsDetailRoute
  '/marketing-meetings': typeof MarketingMeetingsRoute
  '/media': typeof MediaRoute
  '/media-register': typeof MediaRegisterRoute
  '/new-lead': typeof NewLeadRoute
  '/okrs': typeof OkrsRoute
  '/partner-portal': typeof PartnerPortalRoute
  '/partners': typeof PartnersRoute
  '/pipeline': typeof PipelineRoute
  '/playbooks': typeof PlaybooksRoute
  '/realtor-portal': typeof RealtorPortalRoute
  '/retention': typeof RetentionRoute
  '/revenue-command': typeof RevenueCommandRoute
  '/role-governance': typeof RoleGovernanceRoute
  '/support': typeof SupportRoute
  '/team-directory': typeof TeamDirectoryRoute
  '/turnaround': typeof TurnaroundRoute
  '/whatsapp': typeof WhatsappRoute
  '/workdesk': typeof WorkdeskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/coaching': typeof CoachingRoute
  '/compliance': typeof ComplianceRoute
  '/content-studio': typeof ContentStudioRoute
  '/daily-execution': typeof DailyExecutionRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/email-center': typeof EmailCenterRoute
  '/forecast': typeof ForecastRoute
  '/funnel-audit': typeof FunnelAuditRoute
  '/handoff': typeof HandoffRoute
  '/integrations': typeof IntegrationsRoute
  '/lead-control': typeof LeadControlRoute
  '/lead-journal': typeof LeadJournalRoute
  '/leads-detail': typeof LeadsDetailRoute
  '/marketing-meetings': typeof MarketingMeetingsRoute
  '/media': typeof MediaRoute
  '/media-register': typeof MediaRegisterRoute
  '/new-lead': typeof NewLeadRoute
  '/okrs': typeof OkrsRoute
  '/partner-portal': typeof PartnerPortalRoute
  '/partners': typeof PartnersRoute
  '/pipeline': typeof PipelineRoute
  '/playbooks': typeof PlaybooksRoute
  '/realtor-portal': typeof RealtorPortalRoute
  '/retention': typeof RetentionRoute
  '/revenue-command': typeof RevenueCommandRoute
  '/role-governance': typeof RoleGovernanceRoute
  '/support': typeof SupportRoute
  '/team-directory': typeof TeamDirectoryRoute
  '/turnaround': typeof TurnaroundRoute
  '/whatsapp': typeof WhatsappRoute
  '/workdesk': typeof WorkdeskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/coaching': typeof CoachingRoute
  '/compliance': typeof ComplianceRoute
  '/content-studio': typeof ContentStudioRoute
  '/daily-execution': typeof DailyExecutionRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/email-center': typeof EmailCenterRoute
  '/forecast': typeof ForecastRoute
  '/funnel-audit': typeof FunnelAuditRoute
  '/handoff': typeof HandoffRoute
  '/integrations': typeof IntegrationsRoute
  '/lead-control': typeof LeadControlRoute
  '/lead-journal': typeof LeadJournalRoute
  '/leads-detail': typeof LeadsDetailRoute
  '/marketing-meetings': typeof MarketingMeetingsRoute
  '/media': typeof MediaRoute
  '/media-register': typeof MediaRegisterRoute
  '/new-lead': typeof NewLeadRoute
  '/okrs': typeof OkrsRoute
  '/partner-portal': typeof PartnerPortalRoute
  '/partners': typeof PartnersRoute
  '/pipeline': typeof PipelineRoute
  '/playbooks': typeof PlaybooksRoute
  '/realtor-portal': typeof RealtorPortalRoute
  '/retention': typeof RetentionRoute
  '/revenue-command': typeof RevenueCommandRoute
  '/role-governance': typeof RoleGovernanceRoute
  '/support': typeof SupportRoute
  '/team-directory': typeof TeamDirectoryRoute
  '/turnaround': typeof TurnaroundRoute
  '/whatsapp': typeof WhatsappRoute
  '/workdesk': typeof WorkdeskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-log'
    | '/calendar'
    | '/campaigns'
    | '/coaching'
    | '/compliance'
    | '/content-studio'
    | '/daily-execution'
    | '/dashboard'
    | '/design'
    | '/email-center'
    | '/forecast'
    | '/funnel-audit'
    | '/handoff'
    | '/integrations'
    | '/lead-control'
    | '/lead-journal'
    | '/leads-detail'
    | '/marketing-meetings'
    | '/media'
    | '/media-register'
    | '/new-lead'
    | '/okrs'
    | '/partner-portal'
    | '/partners'
    | '/pipeline'
    | '/playbooks'
    | '/realtor-portal'
    | '/retention'
    | '/revenue-command'
    | '/role-governance'
    | '/support'
    | '/team-directory'
    | '/turnaround'
    | '/whatsapp'
    | '/workdesk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-log'
    | '/calendar'
    | '/campaigns'
    | '/coaching'
    | '/compliance'
    | '/content-studio'
    | '/daily-execution'
    | '/dashboard'
    | '/design'
    | '/email-center'
    | '/forecast'
    | '/funnel-audit'
    | '/handoff'
    | '/integrations'
    | '/lead-control'
    | '/lead-journal'
    | '/leads-detail'
    | '/marketing-meetings'
    | '/media'
    | '/media-register'
    | '/new-lead'
    | '/okrs'
    | '/partner-portal'
    | '/partners'
    | '/pipeline'
    | '/playbooks'
    | '/realtor-portal'
    | '/retention'
    | '/revenue-command'
    | '/role-governance'
    | '/support'
    | '/team-directory'
    | '/turnaround'
    | '/whatsapp'
    | '/workdesk'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-log'
    | '/calendar'
    | '/campaigns'
    | '/coaching'
    | '/compliance'
    | '/content-studio'
    | '/daily-execution'
    | '/dashboard'
    | '/design'
    | '/email-center'
    | '/forecast'
    | '/funnel-audit'
    | '/handoff'
    | '/integrations'
    | '/lead-control'
    | '/lead-journal'
    | '/leads-detail'
    | '/marketing-meetings'
    | '/media'
    | '/media-register'
    | '/new-lead'
    | '/okrs'
    | '/partner-portal'
    | '/partners'
    | '/pipeline'
    | '/playbooks'
    | '/realtor-portal'
    | '/retention'
    | '/revenue-command'
    | '/role-governance'
    | '/support'
    | '/team-directory'
    | '/turnaround'
    | '/whatsapp'
    | '/workdesk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogRoute: typeof AuditLogRoute
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRoute
  CoachingRoute: typeof CoachingRoute
  ComplianceRoute: typeof ComplianceRoute
  ContentStudioRoute: typeof ContentStudioRoute
  DailyExecutionRoute: typeof DailyExecutionRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  EmailCenterRoute: typeof EmailCenterRoute
  ForecastRoute: typeof ForecastRoute
  FunnelAuditRoute: typeof FunnelAuditRoute
  HandoffRoute: typeof HandoffRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LeadControlRoute: typeof LeadControlRoute
  LeadJournalRoute: typeof LeadJournalRoute
  LeadsDetailRoute: typeof LeadsDetailRoute
  MarketingMeetingsRoute: typeof MarketingMeetingsRoute
  MediaRoute: typeof MediaRoute
  MediaRegisterRoute: typeof MediaRegisterRoute
  NewLeadRoute: typeof NewLeadRoute
  OkrsRoute: typeof OkrsRoute
  PartnerPortalRoute: typeof PartnerPortalRoute
  PartnersRoute: typeof PartnersRoute
  PipelineRoute: typeof PipelineRoute
  PlaybooksRoute: typeof PlaybooksRoute
  RealtorPortalRoute: typeof RealtorPortalRoute
  RetentionRoute: typeof RetentionRoute
  RevenueCommandRoute: typeof RevenueCommandRoute
  RoleGovernanceRoute: typeof RoleGovernanceRoute
  SupportRoute: typeof SupportRoute
  TeamDirectoryRoute: typeof TeamDirectoryRoute
  TurnaroundRoute: typeof TurnaroundRoute
  WhatsappRoute: typeof WhatsappRoute
  WorkdeskRoute: typeof WorkdeskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-studio': {
      id: '/content-studio'
      path: '/content-studio'
      fullPath: '/content-studio'
      preLoaderRoute: typeof ContentStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-execution': {
      id: '/daily-execution'
      path: '/daily-execution'
      fullPath: '/daily-execution'
      preLoaderRoute: typeof DailyExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-center': {
      id: '/email-center'
      path: '/email-center'
      fullPath: '/email-center'
      preLoaderRoute: typeof EmailCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel-audit': {
      id: '/funnel-audit'
      path: '/funnel-audit'
      fullPath: '/funnel-audit'
      preLoaderRoute: typeof FunnelAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-control': {
      id: '/lead-control'
      path: '/lead-control'
      fullPath: '/lead-control'
      preLoaderRoute: typeof LeadControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-journal': {
      id: '/lead-journal'
      path: '/lead-journal'
      fullPath: '/lead-journal'
      preLoaderRoute: typeof LeadJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-detail': {
      id: '/leads-detail'
      path: '/leads-detail'
      fullPath: '/leads-detail'
      preLoaderRoute: typeof LeadsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-meetings': {
      id: '/marketing-meetings'
      path: '/marketing-meetings'
      fullPath: '/marketing-meetings'
      preLoaderRoute: typeof MarketingMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-register': {
      id: '/media-register'
      path: '/media-register'
      fullPath: '/media-register'
      preLoaderRoute: typeof MediaRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-lead': {
      id: '/new-lead'
      path: '/new-lead'
      fullPath: '/new-lead'
      preLoaderRoute: typeof NewLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okrs': {
      id: '/okrs'
      path: '/okrs'
      fullPath: '/okrs'
      preLoaderRoute: typeof OkrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-portal': {
      id: '/partner-portal'
      path: '/partner-portal'
      fullPath: '/partner-portal'
      preLoaderRoute: typeof PartnerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtor-portal': {
      id: '/realtor-portal'
      path: '/realtor-portal'
      fullPath: '/realtor-portal'
      preLoaderRoute: typeof RealtorPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retention': {
      id: '/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof RetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-command': {
      id: '/revenue-command'
      path: '/revenue-command'
      fullPath: '/revenue-command'
      preLoaderRoute: typeof RevenueCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-governance': {
      id: '/role-governance'
      path: '/role-governance'
      fullPath: '/role-governance'
      preLoaderRoute: typeof RoleGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-directory': {
      id: '/team-directory'
      path: '/team-directory'
      fullPath: '/team-directory'
      preLoaderRoute: typeof TeamDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnaround': {
      id: '/turnaround'
      path: '/turnaround'
      fullPath: '/turnaround'
      preLoaderRoute: typeof TurnaroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workdesk': {
      id: '/workdesk'
      path: '/workdesk'
      fullPath: '/workdesk'
      preLoaderRoute: typeof WorkdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogRoute: AuditLogRoute,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRoute,
  CoachingRoute: CoachingRoute,
  ComplianceRoute: ComplianceRoute,
  ContentStudioRoute: ContentStudioRoute,
  DailyExecutionRoute: DailyExecutionRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  EmailCenterRoute: EmailCenterRoute,
  ForecastRoute: ForecastRoute,
  FunnelAuditRoute: FunnelAuditRoute,
  HandoffRoute: HandoffRoute,
  IntegrationsRoute: IntegrationsRoute,
  LeadControlRoute: LeadControlRoute,
  LeadJournalRoute: LeadJournalRoute,
  LeadsDetailRoute: LeadsDetailRoute,
  MarketingMeetingsRoute: MarketingMeetingsRoute,
  MediaRoute: MediaRoute,
  MediaRegisterRoute: MediaRegisterRoute,
  NewLeadRoute: NewLeadRoute,
  OkrsRoute: OkrsRoute,
  PartnerPortalRoute: PartnerPortalRoute,
  PartnersRoute: PartnersRoute,
  PipelineRoute: PipelineRoute,
  PlaybooksRoute: PlaybooksRoute,
  RealtorPortalRoute: RealtorPortalRoute,
  RetentionRoute: RetentionRoute,
  RevenueCommandRoute: RevenueCommandRoute,
  RoleGovernanceRoute: RoleGovernanceRoute,
  SupportRoute: SupportRoute,
  TeamDirectoryRoute: TeamDirectoryRoute,
  TurnaroundRoute: TurnaroundRoute,
  WhatsappRoute: WhatsappRoute,
  WorkdeskRoute: WorkdeskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
